import type { Wine } from "@/types/wine"

// Mock data to use as fallback when Google Sheets API fails
export const MOCK_WINES: Wine[] = [
  {
    id: "1",
    nombre: "Gran Reserva Malbec",
    productor: "Bodega Catena Zapata",
    region: "Mendoza",
    pais: "Argentina",
    ano: "2018",
    uva: "Malbec",
    alcohol: "14.5%",
    enologo: "Laura Catena",
    precio: "$85",
    precioCopaR1: "$22",
    precioCopaR2: "$15",
    vista: "Rojo intenso con reflejos violáceos",
    nariz: "Aromas a frutos negros, vainilla y especias",
    boca: "Taninos suaves, final persistente",
    maridaje: "Carnes rojas, cordero",
    estilo: "Tinto de cuerpo completo",
    tipo: "Tinto",
    caracteristica: "Vino Tinto Malbec",
  },
  {
    id: "2",
    nombre: "Chardonnay Reserva",
    productor: "Viña Concha y Toro",
    region: "Valle de Casablanca",
    pais: "Chile",
    ano: "2020",
    uva: "Chardonnay",
    alcohol: "13.5%",
    precio: "$45",
    precioCopaR1: "$12",
    vista: "Amarillo pálido con reflejos verdosos",
    nariz: "Notas de frutas tropicales y vainilla",
    boca: "Fresco, con buena acidez y final largo",
    maridaje: "Pescados, mariscos, quesos suaves",
    estilo: "Blanco con crianza en barrica",
    tipo: "Blanco",
    caracteristica: "Vino Blanco Chardonnay",
  },
  {
    id: "3",
    nombre: "Brut Nature Rosé",
    productor: "Champagne Billecart-Salmon",
    region: "Champagne",
    pais: "Francia",
    ano: "NV",
    uva: "Pinot Noir, Chardonnay",
    alcohol: "12%",
    precio: "$120",
    vista: "Rosa pálido con burbujas finas",
    nariz: "Fresas, frambuesas y notas de pan tostado",
    boca: "Fresco, elegante, con final largo",
    maridaje: "Aperitivos, mariscos, postres de frutas",
    estilo: "Espumoso Brut Nature",
    tipo: "Espumante",
    caracteristica: "Vino Espumante Rosé",
  },
  {
    id: "4",
    nombre: "Rosé de Provence",
    productor: "Château Minuty",
    region: "Provence",
    pais: "Francia",
    ano: "2021",
    uva: "Grenache, Cinsault, Syrah",
    alcohol: "12.5%",
    precio: "$55",
    precioCopaR1: "$14",
    vista: "Rosa pálido con reflejos salmón",
    nariz: "Frutas rojas frescas y cítricos",
    boca: "Seco, fresco, con final mineral",
    maridaje: "Ensaladas, pescados, cocina mediterránea",
    estilo: "Rosado seco",
    tipo: "Rosado",
    caracteristica: "Vino Rosado",
  },
]
